"""Registry of all 650 UK Parliament constituencies as used at the
4 July 2024 General Election (PCON_JUL_2024 boundary set).

Each tuple is (PCON24CD, display_name, wikipedia_article_title).
Codes are real ONS PCON_JUL_2024 codes sourced from
PCON_2024_UK_NC_v2 on the ONS Open Geography Portal.

Wikipedia article titles follow the canonical
``"<name> (UK Parliament constituency)"`` pattern. Scripts 19 and 20
share this list; 21 reuses the codes to filter the boundary GeoJSON.

NI (N05*) constituencies are listed for completeness but are filtered
out at render time in 07d: the gb viewBox excludes NI, so the 18 NI
seats are deferred until a future NI render decision (see issue #26).
"""

GE2024_CONSTITUENCIES: list[tuple[str, str, str]] = [
    # England (543 seats)
    ('E14001063', 'Aldershot', 'Aldershot (UK Parliament constituency)'),
    ('E14001064', 'Aldridge-Brownhills', 'Aldridge-Brownhills (UK Parliament constituency)'),
    ('E14001065', 'Altrincham and Sale West', 'Altrincham and Sale West (UK Parliament constituency)'),
    ('E14001066', 'Amber Valley', 'Amber Valley (UK Parliament constituency)'),
    ('E14001067', 'Arundel and South Downs', 'Arundel and South Downs (UK Parliament constituency)'),
    ('E14001068', 'Ashfield', 'Ashfield (UK Parliament constituency)'),
    ('E14001069', 'Ashford', 'Ashford (UK Parliament constituency)'),
    ('E14001070', 'Ashton-under-Lyne', 'Ashton-under-Lyne (UK Parliament constituency)'),
    ('E14001071', 'Aylesbury', 'Aylesbury (UK Parliament constituency)'),
    ('E14001072', 'Banbury', 'Banbury (UK Parliament constituency)'),
    ('E14001073', 'Barking', 'Barking (UK Parliament constituency)'),
    ('E14001074', 'Barnsley North', 'Barnsley North (UK Parliament constituency)'),
    ('E14001075', 'Barnsley South', 'Barnsley South (UK Parliament constituency)'),
    ('E14001076', 'Barrow and Furness', 'Barrow and Furness (UK Parliament constituency)'),
    ('E14001077', 'Basildon and Billericay', 'Basildon and Billericay (UK Parliament constituency)'),
    ('E14001078', 'Basingstoke', 'Basingstoke (UK Parliament constituency)'),
    ('E14001079', 'Bassetlaw', 'Bassetlaw (UK Parliament constituency)'),
    ('E14001080', 'Bath', 'Bath (UK Parliament constituency)'),
    ('E14001081', 'Battersea', 'Battersea (UK Parliament constituency)'),
    ('E14001082', 'Beaconsfield', 'Beaconsfield (UK Parliament constituency)'),
    ('E14001083', 'Beckenham and Penge', 'Beckenham and Penge (UK Parliament constituency)'),
    ('E14001084', 'Bedford', 'Bedford (UK Parliament constituency)'),
    ('E14001085', 'Bermondsey and Old Southwark', 'Bermondsey and Old Southwark (UK Parliament constituency)'),
    ('E14001086', 'Bethnal Green and Stepney', 'Bethnal Green and Stepney (UK Parliament constituency)'),
    ('E14001087', 'Beverley and Holderness', 'Beverley and Holderness (UK Parliament constituency)'),
    ('E14001088', 'Bexhill and Battle', 'Bexhill and Battle (UK Parliament constituency)'),
    ('E14001089', 'Bexleyheath and Crayford', 'Bexleyheath and Crayford (UK Parliament constituency)'),
    ('E14001090', 'Bicester and Woodstock', 'Bicester and Woodstock (UK Parliament constituency)'),
    ('E14001091', 'Birkenhead', 'Birkenhead (UK Parliament constituency)'),
    ('E14001092', 'Birmingham Edgbaston', 'Birmingham Edgbaston (UK Parliament constituency)'),
    ('E14001093', 'Birmingham Erdington', 'Birmingham Erdington (UK Parliament constituency)'),
    ('E14001094', 'Birmingham Hall Green and Moseley', 'Birmingham Hall Green and Moseley (UK Parliament constituency)'),
    ('E14001095', 'Birmingham Hodge Hill and Solihull North', 'Birmingham Hodge Hill and Solihull North (UK Parliament constituency)'),
    ('E14001096', 'Birmingham Ladywood', 'Birmingham Ladywood (UK Parliament constituency)'),
    ('E14001097', 'Birmingham Northfield', 'Birmingham Northfield (UK Parliament constituency)'),
    ('E14001098', 'Birmingham Perry Barr', 'Birmingham Perry Barr (UK Parliament constituency)'),
    ('E14001099', 'Birmingham Selly Oak', 'Birmingham Selly Oak (UK Parliament constituency)'),
    ('E14001100', 'Birmingham Yardley', 'Birmingham Yardley (UK Parliament constituency)'),
    ('E14001101', 'Bishop Auckland', 'Bishop Auckland (UK Parliament constituency)'),
    ('E14001102', 'Blackburn', 'Blackburn (UK Parliament constituency)'),
    ('E14001103', 'Blackley and Middleton South', 'Blackley and Middleton South (UK Parliament constituency)'),
    ('E14001104', 'Blackpool North and Fleetwood', 'Blackpool North and Fleetwood (UK Parliament constituency)'),
    ('E14001105', 'Blackpool South', 'Blackpool South (UK Parliament constituency)'),
    ('E14001106', 'Blaydon and Consett', 'Blaydon and Consett (UK Parliament constituency)'),
    ('E14001107', 'Blyth and Ashington', 'Blyth and Ashington (UK Parliament constituency)'),
    ('E14001108', 'Bognor Regis and Littlehampton', 'Bognor Regis and Littlehampton (UK Parliament constituency)'),
    ('E14001109', 'Bolsover', 'Bolsover (UK Parliament constituency)'),
    ('E14001110', 'Bolton North East', 'Bolton North East (UK Parliament constituency)'),
    ('E14001111', 'Bolton South and Walkden', 'Bolton South and Walkden (UK Parliament constituency)'),
    ('E14001112', 'Bolton West', 'Bolton West (UK Parliament constituency)'),
    ('E14001113', 'Bootle', 'Bootle (UK Parliament constituency)'),
    ('E14001114', 'Boston and Skegness', 'Boston and Skegness (UK Parliament constituency)'),
    ('E14001115', 'Bournemouth East', 'Bournemouth East (UK Parliament constituency)'),
    ('E14001116', 'Bournemouth West', 'Bournemouth West (UK Parliament constituency)'),
    ('E14001117', 'Bracknell', 'Bracknell (UK Parliament constituency)'),
    ('E14001118', 'Bradford East', 'Bradford East (UK Parliament constituency)'),
    ('E14001119', 'Bradford South', 'Bradford South (UK Parliament constituency)'),
    ('E14001120', 'Bradford West', 'Bradford West (UK Parliament constituency)'),
    ('E14001121', 'Braintree', 'Braintree (UK Parliament constituency)'),
    ('E14001122', 'Brent East', 'Brent East (UK Parliament constituency)'),
    ('E14001123', 'Brent West', 'Brent West (UK Parliament constituency)'),
    ('E14001124', 'Brentford and Isleworth', 'Brentford and Isleworth (UK Parliament constituency)'),
    ('E14001125', 'Brentwood and Ongar', 'Brentwood and Ongar (UK Parliament constituency)'),
    ('E14001126', 'Bridgwater', 'Bridgwater (UK Parliament constituency)'),
    ('E14001127', 'Bridlington and The Wolds', 'Bridlington and The Wolds (UK Parliament constituency)'),
    ('E14001128', 'Brigg and Immingham', 'Brigg and Immingham (UK Parliament constituency)'),
    ('E14001129', 'Brighton Kemptown and Peacehaven', 'Brighton Kemptown and Peacehaven (UK Parliament constituency)'),
    ('E14001130', 'Brighton Pavilion', 'Brighton Pavilion (UK Parliament constituency)'),
    ('E14001131', 'Bristol Central', 'Bristol Central (UK Parliament constituency)'),
    ('E14001132', 'Bristol East', 'Bristol East (UK Parliament constituency)'),
    ('E14001133', 'Bristol North East', 'Bristol North East (UK Parliament constituency)'),
    ('E14001134', 'Bristol North West', 'Bristol North West (UK Parliament constituency)'),
    ('E14001135', 'Bristol South', 'Bristol South (UK Parliament constituency)'),
    ('E14001136', 'Broadland and Fakenham', 'Broadland and Fakenham (UK Parliament constituency)'),
    ('E14001137', 'Bromley and Biggin Hill', 'Bromley and Biggin Hill (UK Parliament constituency)'),
    ('E14001138', 'Bromsgrove', 'Bromsgrove (UK Parliament constituency)'),
    ('E14001139', 'Broxbourne', 'Broxbourne (UK Parliament constituency)'),
    ('E14001140', 'Broxtowe', 'Broxtowe (UK Parliament constituency)'),
    ('E14001141', 'Buckingham and Bletchley', 'Buckingham and Bletchley (UK Parliament constituency)'),
    ('E14001142', 'Burnley', 'Burnley (UK Parliament constituency)'),
    ('E14001143', 'Burton and Uttoxeter', 'Burton and Uttoxeter (UK Parliament constituency)'),
    ('E14001144', 'Bury North', 'Bury North (UK Parliament constituency)'),
    ('E14001145', 'Bury South', 'Bury South (UK Parliament constituency)'),
    ('E14001146', 'Bury St Edmunds and Stowmarket', 'Bury St Edmunds and Stowmarket (UK Parliament constituency)'),
    ('E14001147', 'Calder Valley', 'Calder Valley (UK Parliament constituency)'),
    ('E14001148', 'Camborne and Redruth', 'Camborne and Redruth (UK Parliament constituency)'),
    ('E14001149', 'Cambridge', 'Cambridge (UK Parliament constituency)'),
    ('E14001150', 'Cannock Chase', 'Cannock Chase (UK Parliament constituency)'),
    ('E14001151', 'Canterbury', 'Canterbury (UK Parliament constituency)'),
    ('E14001152', 'Carlisle', 'Carlisle (UK Parliament constituency)'),
    ('E14001153', 'Carshalton and Wallington', 'Carshalton and Wallington (UK Parliament constituency)'),
    ('E14001154', 'Castle Point', 'Castle Point (UK Parliament constituency)'),
    ('E14001155', 'Central Devon', 'Central Devon (UK Parliament constituency)'),
    ('E14001156', 'Central Suffolk and North Ipswich', 'Central Suffolk and North Ipswich (UK Parliament constituency)'),
    ('E14001157', 'Chatham and Aylesford', 'Chatham and Aylesford (UK Parliament constituency)'),
    ('E14001158', 'Cheadle', 'Cheadle (UK Parliament constituency)'),
    ('E14001159', 'Chelmsford', 'Chelmsford (UK Parliament constituency)'),
    ('E14001160', 'Chelsea and Fulham', 'Chelsea and Fulham (UK Parliament constituency)'),
    ('E14001161', 'Cheltenham', 'Cheltenham (UK Parliament constituency)'),
    ('E14001162', 'Chesham and Amersham', 'Chesham and Amersham (UK Parliament constituency)'),
    ('E14001163', 'Chester North and Neston', 'Chester North and Neston (UK Parliament constituency)'),
    ('E14001164', 'Chester South and Eddisbury', 'Chester South and Eddisbury (UK Parliament constituency)'),
    ('E14001165', 'Chesterfield', 'Chesterfield (UK Parliament constituency)'),
    ('E14001166', 'Chichester', 'Chichester (UK Parliament constituency)'),
    ('E14001167', 'Chingford and Woodford Green', 'Chingford and Woodford Green (UK Parliament constituency)'),
    ('E14001168', 'Chippenham', 'Chippenham (UK Parliament constituency)'),
    ('E14001169', 'Chipping Barnet', 'Chipping Barnet (UK Parliament constituency)'),
    ('E14001170', 'Chorley', 'Chorley (UK Parliament constituency)'),
    ('E14001171', 'Christchurch', 'Christchurch (UK Parliament constituency)'),
    ('E14001172', 'Cities of London and Westminster', 'Cities of London and Westminster (UK Parliament constituency)'),
    ('E14001173', 'City of Durham', 'City of Durham (UK Parliament constituency)'),
    ('E14001174', 'Clacton', 'Clacton (UK Parliament constituency)'),
    ('E14001175', 'Clapham and Brixton Hill', 'Clapham and Brixton Hill (UK Parliament constituency)'),
    ('E14001176', 'Colchester', 'Colchester (UK Parliament constituency)'),
    ('E14001177', 'Colne Valley', 'Colne Valley (UK Parliament constituency)'),
    ('E14001178', 'Congleton', 'Congleton (UK Parliament constituency)'),
    ('E14001179', 'Corby and East Northamptonshire', 'Corby and East Northamptonshire (UK Parliament constituency)'),
    ('E14001180', 'Coventry East', 'Coventry East (UK Parliament constituency)'),
    ('E14001181', 'Coventry North West', 'Coventry North West (UK Parliament constituency)'),
    ('E14001182', 'Coventry South', 'Coventry South (UK Parliament constituency)'),
    ('E14001183', 'Cramlington and Killingworth', 'Cramlington and Killingworth (UK Parliament constituency)'),
    ('E14001184', 'Crawley', 'Crawley (UK Parliament constituency)'),
    ('E14001185', 'Crewe and Nantwich', 'Crewe and Nantwich (UK Parliament constituency)'),
    ('E14001186', 'Croydon East', 'Croydon East (UK Parliament constituency)'),
    ('E14001187', 'Croydon South', 'Croydon South (UK Parliament constituency)'),
    ('E14001188', 'Croydon West', 'Croydon West (UK Parliament constituency)'),
    ('E14001189', 'Dagenham and Rainham', 'Dagenham and Rainham (UK Parliament constituency)'),
    ('E14001190', 'Darlington', 'Darlington (UK Parliament constituency)'),
    ('E14001191', 'Dartford', 'Dartford (UK Parliament constituency)'),
    ('E14001192', 'Daventry', 'Daventry (UK Parliament constituency)'),
    ('E14001193', 'Derby North', 'Derby North (UK Parliament constituency)'),
    ('E14001194', 'Derby South', 'Derby South (UK Parliament constituency)'),
    ('E14001195', 'Derbyshire Dales', 'Derbyshire Dales (UK Parliament constituency)'),
    ('E14001196', 'Dewsbury and Batley', 'Dewsbury and Batley (UK Parliament constituency)'),
    ('E14001197', 'Didcot and Wantage', 'Didcot and Wantage (UK Parliament constituency)'),
    ('E14001198', 'Doncaster Central', 'Doncaster Central (UK Parliament constituency)'),
    ('E14001199', 'Doncaster East and the Isle of Axholme', 'Doncaster East and the Isle of Axholme (UK Parliament constituency)'),
    ('E14001200', 'Doncaster North', 'Doncaster North (UK Parliament constituency)'),
    ('E14001201', 'Dorking and Horley', 'Dorking and Horley (UK Parliament constituency)'),
    ('E14001202', 'Dover and Deal', 'Dover and Deal (UK Parliament constituency)'),
    ('E14001203', 'Droitwich and Evesham', 'Droitwich and Evesham (UK Parliament constituency)'),
    ('E14001204', 'Dudley', 'Dudley (UK Parliament constituency)'),
    ('E14001205', 'Dulwich and West Norwood', 'Dulwich and West Norwood (UK Parliament constituency)'),
    ('E14001206', 'Dunstable and Leighton Buzzard', 'Dunstable and Leighton Buzzard (UK Parliament constituency)'),
    ('E14001207', 'Ealing Central and Acton', 'Ealing Central and Acton (UK Parliament constituency)'),
    ('E14001208', 'Ealing North', 'Ealing North (UK Parliament constituency)'),
    ('E14001209', 'Ealing Southall', 'Ealing Southall (UK Parliament constituency)'),
    ('E14001210', 'Earley and Woodley', 'Earley and Woodley (UK Parliament constituency)'),
    ('E14001211', 'Easington', 'Easington (UK Parliament constituency)'),
    ('E14001212', 'East Grinstead and Uckfield', 'East Grinstead and Uckfield (UK Parliament constituency)'),
    ('E14001213', 'East Ham', 'East Ham (UK Parliament constituency)'),
    ('E14001214', 'East Hampshire', 'East Hampshire (UK Parliament constituency)'),
    ('E14001215', 'East Surrey', 'East Surrey (UK Parliament constituency)'),
    ('E14001216', 'East Thanet', 'East Thanet (UK Parliament constituency)'),
    ('E14001217', 'East Wiltshire', 'East Wiltshire (UK Parliament constituency)'),
    ('E14001218', 'East Worthing and Shoreham', 'East Worthing and Shoreham (UK Parliament constituency)'),
    ('E14001219', 'Eastbourne', 'Eastbourne (UK Parliament constituency)'),
    ('E14001220', 'Eastleigh', 'Eastleigh (UK Parliament constituency)'),
    ('E14001221', 'Edmonton and Winchmore Hill', 'Edmonton and Winchmore Hill (UK Parliament constituency)'),
    ('E14001222', 'Ellesmere Port and Bromborough', 'Ellesmere Port and Bromborough (UK Parliament constituency)'),
    ('E14001223', 'Eltham and Chislehurst', 'Eltham and Chislehurst (UK Parliament constituency)'),
    ('E14001224', 'Ely and East Cambridgeshire', 'Ely and East Cambridgeshire (UK Parliament constituency)'),
    ('E14001225', 'Enfield North', 'Enfield North (UK Parliament constituency)'),
    ('E14001226', 'Epping Forest', 'Epping Forest (UK Parliament constituency)'),
    ('E14001227', 'Epsom and Ewell', 'Epsom and Ewell (UK Parliament constituency)'),
    ('E14001228', 'Erewash', 'Erewash (UK Parliament constituency)'),
    ('E14001229', 'Erith and Thamesmead', 'Erith and Thamesmead (UK Parliament constituency)'),
    ('E14001230', 'Esher and Walton', 'Esher and Walton (UK Parliament constituency)'),
    ('E14001231', 'Exeter', 'Exeter (UK Parliament constituency)'),
    ('E14001232', 'Exmouth and Exeter East', 'Exmouth and Exeter East (UK Parliament constituency)'),
    ('E14001233', 'Fareham and Waterlooville', 'Fareham and Waterlooville (UK Parliament constituency)'),
    ('E14001234', 'Farnham and Bordon', 'Farnham and Bordon (UK Parliament constituency)'),
    ('E14001235', 'Faversham and Mid Kent', 'Faversham and Mid Kent (UK Parliament constituency)'),
    ('E14001236', 'Feltham and Heston', 'Feltham and Heston (UK Parliament constituency)'),
    ('E14001237', 'Filton and Bradley Stoke', 'Filton and Bradley Stoke (UK Parliament constituency)'),
    ('E14001238', 'Finchley and Golders Green', 'Finchley and Golders Green (UK Parliament constituency)'),
    ('E14001239', 'Folkestone and Hythe', 'Folkestone and Hythe (UK Parliament constituency)'),
    ('E14001240', 'Forest of Dean', 'Forest of Dean (UK Parliament constituency)'),
    ('E14001241', 'Frome and East Somerset', 'Frome and East Somerset (UK Parliament constituency)'),
    ('E14001242', 'Fylde', 'Fylde (UK Parliament constituency)'),
    ('E14001243', 'Gainsborough', 'Gainsborough (UK Parliament constituency)'),
    ('E14001244', 'Gateshead Central and Whickham', 'Gateshead Central and Whickham (UK Parliament constituency)'),
    ('E14001245', 'Gedling', 'Gedling (UK Parliament constituency)'),
    ('E14001246', 'Gillingham and Rainham', 'Gillingham and Rainham (UK Parliament constituency)'),
    ('E14001247', 'Glastonbury and Somerton', 'Glastonbury and Somerton (UK Parliament constituency)'),
    ('E14001248', 'Gloucester', 'Gloucester (UK Parliament constituency)'),
    ('E14001249', 'Godalming and Ash', 'Godalming and Ash (UK Parliament constituency)'),
    ('E14001250', 'Goole and Pocklington', 'Goole and Pocklington (UK Parliament constituency)'),
    ('E14001251', 'Gorton and Denton', 'Gorton and Denton (UK Parliament constituency)'),
    ('E14001252', 'Gosport', 'Gosport (UK Parliament constituency)'),
    ('E14001253', 'Grantham and Bourne', 'Grantham and Bourne (UK Parliament constituency)'),
    ('E14001254', 'Gravesham', 'Gravesham (UK Parliament constituency)'),
    ('E14001255', 'Great Grimsby and Cleethorpes', 'Great Grimsby and Cleethorpes (UK Parliament constituency)'),
    ('E14001256', 'Great Yarmouth', 'Great Yarmouth (UK Parliament constituency)'),
    ('E14001257', 'Greenwich and Woolwich', 'Greenwich and Woolwich (UK Parliament constituency)'),
    ('E14001258', 'Guildford', 'Guildford (UK Parliament constituency)'),
    ('E14001259', 'Hackney North and Stoke Newington', 'Hackney North and Stoke Newington (UK Parliament constituency)'),
    ('E14001260', 'Hackney South and Shoreditch', 'Hackney South and Shoreditch (UK Parliament constituency)'),
    ('E14001261', 'Halesowen', 'Halesowen (UK Parliament constituency)'),
    ('E14001262', 'Halifax', 'Halifax (UK Parliament constituency)'),
    ('E14001263', 'Hamble Valley', 'Hamble Valley (UK Parliament constituency)'),
    ('E14001264', 'Hammersmith and Chiswick', 'Hammersmith and Chiswick (UK Parliament constituency)'),
    ('E14001265', 'Hampstead and Highgate', 'Hampstead and Highgate (UK Parliament constituency)'),
    ('E14001266', 'Harborough, Oadby and Wigston', 'Harborough, Oadby and Wigston (UK Parliament constituency)'),
    ('E14001267', 'Harlow', 'Harlow (UK Parliament constituency)'),
    ('E14001268', 'Harpenden and Berkhamsted', 'Harpenden and Berkhamsted (UK Parliament constituency)'),
    ('E14001269', 'Harrogate and Knaresborough', 'Harrogate and Knaresborough (UK Parliament constituency)'),
    ('E14001270', 'Harrow East', 'Harrow East (UK Parliament constituency)'),
    ('E14001271', 'Harrow West', 'Harrow West (UK Parliament constituency)'),
    ('E14001272', 'Hartlepool', 'Hartlepool (UK Parliament constituency)'),
    ('E14001273', 'Harwich and North Essex', 'Harwich and North Essex (UK Parliament constituency)'),
    ('E14001274', 'Hastings and Rye', 'Hastings and Rye (UK Parliament constituency)'),
    ('E14001275', 'Havant', 'Havant (UK Parliament constituency)'),
    ('E14001276', 'Hayes and Harlington', 'Hayes and Harlington (UK Parliament constituency)'),
    ('E14001277', 'Hazel Grove', 'Hazel Grove (UK Parliament constituency)'),
    ('E14001278', 'Hemel Hempstead', 'Hemel Hempstead (UK Parliament constituency)'),
    ('E14001279', 'Hendon', 'Hendon (UK Parliament constituency)'),
    ('E14001280', 'Henley and Thame', 'Henley and Thame (UK Parliament constituency)'),
    ('E14001281', 'Hereford and South Herefordshire', 'Hereford and South Herefordshire (UK Parliament constituency)'),
    ('E14001282', 'Herne Bay and Sandwich', 'Herne Bay and Sandwich (UK Parliament constituency)'),
    ('E14001283', 'Hertford and Stortford', 'Hertford and Stortford (UK Parliament constituency)'),
    ('E14001284', 'Hertsmere', 'Hertsmere (UK Parliament constituency)'),
    ('E14001285', 'Hexham', 'Hexham (UK Parliament constituency)'),
    ('E14001286', 'Heywood and Middleton North', 'Heywood and Middleton North (UK Parliament constituency)'),
    ('E14001287', 'High Peak', 'High Peak (UK Parliament constituency)'),
    ('E14001288', 'Hinckley and Bosworth', 'Hinckley and Bosworth (UK Parliament constituency)'),
    ('E14001289', 'Hitchin', 'Hitchin (UK Parliament constituency)'),
    ('E14001290', 'Holborn and St Pancras', 'Holborn and St Pancras (UK Parliament constituency)'),
    ('E14001291', 'Honiton and Sidmouth', 'Honiton and Sidmouth (UK Parliament constituency)'),
    ('E14001292', 'Hornchurch and Upminster', 'Hornchurch and Upminster (UK Parliament constituency)'),
    ('E14001293', 'Hornsey and Friern Barnet', 'Hornsey and Friern Barnet (UK Parliament constituency)'),
    ('E14001294', 'Horsham', 'Horsham (UK Parliament constituency)'),
    ('E14001295', 'Houghton and Sunderland South', 'Houghton and Sunderland South (UK Parliament constituency)'),
    ('E14001296', 'Hove and Portslade', 'Hove and Portslade (UK Parliament constituency)'),
    ('E14001297', 'Huddersfield', 'Huddersfield (UK Parliament constituency)'),
    ('E14001298', 'Huntingdon', 'Huntingdon (UK Parliament constituency)'),
    ('E14001299', 'Hyndburn', 'Hyndburn (UK Parliament constituency)'),
    ('E14001300', 'Ilford North', 'Ilford North (UK Parliament constituency)'),
    ('E14001301', 'Ilford South', 'Ilford South (UK Parliament constituency)'),
    ('E14001302', 'Ipswich', 'Ipswich (UK Parliament constituency)'),
    ('E14001303', 'Isle of Wight East', 'Isle of Wight East (UK Parliament constituency)'),
    ('E14001304', 'Isle of Wight West', 'Isle of Wight West (UK Parliament constituency)'),
    ('E14001305', 'Islington North', 'Islington North (UK Parliament constituency)'),
    ('E14001306', 'Islington South and Finsbury', 'Islington South and Finsbury (UK Parliament constituency)'),
    ('E14001307', 'Jarrow and Gateshead East', 'Jarrow and Gateshead East (UK Parliament constituency)'),
    ('E14001308', 'Keighley and Ilkley', 'Keighley and Ilkley (UK Parliament constituency)'),
    ('E14001309', 'Kenilworth and Southam', 'Kenilworth and Southam (UK Parliament constituency)'),
    ('E14001310', 'Kensington and Bayswater', 'Kensington and Bayswater (UK Parliament constituency)'),
    ('E14001311', 'Kettering', 'Kettering (UK Parliament constituency)'),
    ('E14001312', 'Kingston and Surbiton', 'Kingston and Surbiton (UK Parliament constituency)'),
    ('E14001313', 'Kingston upon Hull East', 'Kingston upon Hull East (UK Parliament constituency)'),
    ('E14001314', 'Kingston upon Hull North and Cottingham', 'Kingston upon Hull North and Cottingham (UK Parliament constituency)'),
    ('E14001315', 'Kingston upon Hull West and Haltemprice', 'Kingston upon Hull West and Haltemprice (UK Parliament constituency)'),
    ('E14001316', 'Kingswinford and South Staffordshire', 'Kingswinford and South Staffordshire (UK Parliament constituency)'),
    ('E14001317', 'Knowsley', 'Knowsley (UK Parliament constituency)'),
    ('E14001318', 'Lancaster and Wyre', 'Lancaster and Wyre (UK Parliament constituency)'),
    ('E14001319', 'Leeds Central and Headingley', 'Leeds Central and Headingley (UK Parliament constituency)'),
    ('E14001320', 'Leeds East', 'Leeds East (UK Parliament constituency)'),
    ('E14001321', 'Leeds North East', 'Leeds North East (UK Parliament constituency)'),
    ('E14001322', 'Leeds North West', 'Leeds North West (UK Parliament constituency)'),
    ('E14001323', 'Leeds South', 'Leeds South (UK Parliament constituency)'),
    ('E14001324', 'Leeds South West and Morley', 'Leeds South West and Morley (UK Parliament constituency)'),
    ('E14001325', 'Leeds West and Pudsey', 'Leeds West and Pudsey (UK Parliament constituency)'),
    ('E14001326', 'Leicester East', 'Leicester East (UK Parliament constituency)'),
    ('E14001327', 'Leicester South', 'Leicester South (UK Parliament constituency)'),
    ('E14001328', 'Leicester West', 'Leicester West (UK Parliament constituency)'),
    ('E14001329', 'Leigh and Atherton', 'Leigh and Atherton (UK Parliament constituency)'),
    ('E14001330', 'Lewes', 'Lewes (UK Parliament constituency)'),
    ('E14001331', 'Lewisham East', 'Lewisham East (UK Parliament constituency)'),
    ('E14001332', 'Lewisham North', 'Lewisham North (UK Parliament constituency)'),
    ('E14001333', 'Lewisham West and East Dulwich', 'Lewisham West and East Dulwich (UK Parliament constituency)'),
    ('E14001334', 'Leyton and Wanstead', 'Leyton and Wanstead (UK Parliament constituency)'),
    ('E14001335', 'Lichfield', 'Lichfield (UK Parliament constituency)'),
    ('E14001336', 'Lincoln', 'Lincoln (UK Parliament constituency)'),
    ('E14001337', 'Liverpool Garston', 'Liverpool Garston (UK Parliament constituency)'),
    ('E14001338', 'Liverpool Riverside', 'Liverpool Riverside (UK Parliament constituency)'),
    ('E14001339', 'Liverpool Walton', 'Liverpool Walton (UK Parliament constituency)'),
    ('E14001340', 'Liverpool Wavertree', 'Liverpool Wavertree (UK Parliament constituency)'),
    ('E14001341', 'Liverpool West Derby', 'Liverpool West Derby (UK Parliament constituency)'),
    ('E14001342', 'Loughborough', 'Loughborough (UK Parliament constituency)'),
    ('E14001343', 'Louth and Horncastle', 'Louth and Horncastle (UK Parliament constituency)'),
    ('E14001344', 'Lowestoft', 'Lowestoft (UK Parliament constituency)'),
    ('E14001345', 'Luton North', 'Luton North (UK Parliament constituency)'),
    ('E14001346', 'Luton South and South Bedfordshire', 'Luton South and South Bedfordshire (UK Parliament constituency)'),
    ('E14001347', 'Macclesfield', 'Macclesfield (UK Parliament constituency)'),
    ('E14001348', 'Maidenhead', 'Maidenhead (UK Parliament constituency)'),
    ('E14001349', 'Maidstone and Malling', 'Maidstone and Malling (UK Parliament constituency)'),
    ('E14001350', 'Makerfield', 'Makerfield (UK Parliament constituency)'),
    ('E14001351', 'Maldon', 'Maldon (UK Parliament constituency)'),
    ('E14001352', 'Manchester Central', 'Manchester Central (UK Parliament constituency)'),
    ('E14001353', 'Manchester Rusholme', 'Manchester Rusholme (UK Parliament constituency)'),
    ('E14001354', 'Manchester Withington', 'Manchester Withington (UK Parliament constituency)'),
    ('E14001355', 'Mansfield', 'Mansfield (UK Parliament constituency)'),
    ('E14001356', 'Melksham and Devizes', 'Melksham and Devizes (UK Parliament constituency)'),
    ('E14001357', 'Melton and Syston', 'Melton and Syston (UK Parliament constituency)'),
    ('E14001358', 'Meriden and Solihull East', 'Meriden and Solihull East (UK Parliament constituency)'),
    ('E14001359', 'Mid Bedfordshire', 'Mid Bedfordshire (UK Parliament constituency)'),
    ('E14001360', 'Mid Buckinghamshire', 'Mid Buckinghamshire (UK Parliament constituency)'),
    ('E14001361', 'Mid Cheshire', 'Mid Cheshire (UK Parliament constituency)'),
    ('E14001362', 'Mid Derbyshire', 'Mid Derbyshire (UK Parliament constituency)'),
    ('E14001363', 'Mid Dorset and North Poole', 'Mid Dorset and North Poole (UK Parliament constituency)'),
    ('E14001364', 'Mid Leicestershire', 'Mid Leicestershire (UK Parliament constituency)'),
    ('E14001365', 'Mid Norfolk', 'Mid Norfolk (UK Parliament constituency)'),
    ('E14001366', 'Mid Sussex', 'Mid Sussex (UK Parliament constituency)'),
    ('E14001368', 'Middlesbrough South and East Cleveland', 'Middlesbrough South and East Cleveland (UK Parliament constituency)'),
    ('E14001367', 'Middlesbrough and Thornaby East', 'Middlesbrough and Thornaby East (UK Parliament constituency)'),
    ('E14001369', 'Milton Keynes Central', 'Milton Keynes Central (UK Parliament constituency)'),
    ('E14001370', 'Milton Keynes North', 'Milton Keynes North (UK Parliament constituency)'),
    ('E14001371', 'Mitcham and Morden', 'Mitcham and Morden (UK Parliament constituency)'),
    ('E14001372', 'Morecambe and Lunesdale', 'Morecambe and Lunesdale (UK Parliament constituency)'),
    ('E14001373', 'New Forest East', 'New Forest East (UK Parliament constituency)'),
    ('E14001374', 'New Forest West', 'New Forest West (UK Parliament constituency)'),
    ('E14001375', 'Newark', 'Newark (UK Parliament constituency)'),
    ('E14001376', 'Newbury', 'Newbury (UK Parliament constituency)'),
    ('E14001377', 'Newcastle upon Tyne Central and West', 'Newcastle upon Tyne Central and West (UK Parliament constituency)'),
    ('E14001378', 'Newcastle upon Tyne East and Wallsend', 'Newcastle upon Tyne East and Wallsend (UK Parliament constituency)'),
    ('E14001379', 'Newcastle upon Tyne North', 'Newcastle upon Tyne North (UK Parliament constituency)'),
    ('E14001380', 'Newcastle-under-Lyme', 'Newcastle-under-Lyme (UK Parliament constituency)'),
    ('E14001381', 'Newton Abbot', 'Newton Abbot (UK Parliament constituency)'),
    ('E14001382', 'Newton Aycliffe and Spennymoor', 'Newton Aycliffe and Spennymoor (UK Parliament constituency)'),
    ('E14001383', 'Normanton and Hemsworth', 'Normanton and Hemsworth (UK Parliament constituency)'),
    ('E14001384', 'North Bedfordshire', 'North Bedfordshire (UK Parliament constituency)'),
    ('E14001385', 'North Cornwall', 'North Cornwall (UK Parliament constituency)'),
    ('E14001386', 'North Cotswolds', 'North Cotswolds (UK Parliament constituency)'),
    ('E14001387', 'North Devon', 'North Devon (UK Parliament constituency)'),
    ('E14001388', 'North Dorset', 'North Dorset (UK Parliament constituency)'),
    ('E14001389', 'North Durham', 'North Durham (UK Parliament constituency)'),
    ('E14001390', 'North East Cambridgeshire', 'North East Cambridgeshire (UK Parliament constituency)'),
    ('E14001391', 'North East Derbyshire', 'North East Derbyshire (UK Parliament constituency)'),
    ('E14001392', 'North East Hampshire', 'North East Hampshire (UK Parliament constituency)'),
    ('E14001393', 'North East Hertfordshire', 'North East Hertfordshire (UK Parliament constituency)'),
    ('E14001394', 'North East Somerset and Hanham', 'North East Somerset and Hanham (UK Parliament constituency)'),
    ('E14001395', 'North Herefordshire', 'North Herefordshire (UK Parliament constituency)'),
    ('E14001396', 'North Norfolk', 'North Norfolk (UK Parliament constituency)'),
    ('E14001397', 'North Northumberland', 'North Northumberland (UK Parliament constituency)'),
    ('E14001398', 'North Shropshire', 'North Shropshire (UK Parliament constituency)'),
    ('E14001399', 'North Somerset', 'North Somerset (UK Parliament constituency)'),
    ('E14001400', 'North Warwickshire and Bedworth', 'North Warwickshire and Bedworth (UK Parliament constituency)'),
    ('E14001401', 'North West Cambridgeshire', 'North West Cambridgeshire (UK Parliament constituency)'),
    ('E14001402', 'North West Essex', 'North West Essex (UK Parliament constituency)'),
    ('E14001403', 'North West Hampshire', 'North West Hampshire (UK Parliament constituency)'),
    ('E14001404', 'North West Leicestershire', 'North West Leicestershire (UK Parliament constituency)'),
    ('E14001405', 'North West Norfolk', 'North West Norfolk (UK Parliament constituency)'),
    ('E14001406', 'Northampton North', 'Northampton North (UK Parliament constituency)'),
    ('E14001407', 'Northampton South', 'Northampton South (UK Parliament constituency)'),
    ('E14001408', 'Norwich North', 'Norwich North (UK Parliament constituency)'),
    ('E14001409', 'Norwich South', 'Norwich South (UK Parliament constituency)'),
    ('E14001410', 'Nottingham East', 'Nottingham East (UK Parliament constituency)'),
    ('E14001411', 'Nottingham North and Kimberley', 'Nottingham North and Kimberley (UK Parliament constituency)'),
    ('E14001412', 'Nottingham South', 'Nottingham South (UK Parliament constituency)'),
    ('E14001413', 'Nuneaton', 'Nuneaton (UK Parliament constituency)'),
    ('E14001414', 'Old Bexley and Sidcup', 'Old Bexley and Sidcup (UK Parliament constituency)'),
    ('E14001415', 'Oldham East and Saddleworth', 'Oldham East and Saddleworth (UK Parliament constituency)'),
    ('E14001416', 'Oldham West, Chadderton and Royton', 'Oldham West, Chadderton and Royton (UK Parliament constituency)'),
    ('E14001417', 'Orpington', 'Orpington (UK Parliament constituency)'),
    ('E14001418', 'Ossett and Denby Dale', 'Ossett and Denby Dale (UK Parliament constituency)'),
    ('E14001419', 'Oxford East', 'Oxford East (UK Parliament constituency)'),
    ('E14001420', 'Oxford West and Abingdon', 'Oxford West and Abingdon (UK Parliament constituency)'),
    ('E14001421', 'Peckham', 'Peckham (UK Parliament constituency)'),
    ('E14001422', 'Pendle and Clitheroe', 'Pendle and Clitheroe (UK Parliament constituency)'),
    ('E14001423', 'Penistone and Stocksbridge', 'Penistone and Stocksbridge (UK Parliament constituency)'),
    ('E14001424', 'Penrith and Solway', 'Penrith and Solway (UK Parliament constituency)'),
    ('E14001425', 'Peterborough', 'Peterborough (UK Parliament constituency)'),
    ('E14001426', 'Plymouth Moor View', 'Plymouth Moor View (UK Parliament constituency)'),
    ('E14001427', 'Plymouth Sutton and Devonport', 'Plymouth Sutton and Devonport (UK Parliament constituency)'),
    ('E14001428', 'Pontefract, Castleford and Knottingley', 'Pontefract, Castleford and Knottingley (UK Parliament constituency)'),
    ('E14001429', 'Poole', 'Poole (UK Parliament constituency)'),
    ('E14001430', 'Poplar and Limehouse', 'Poplar and Limehouse (UK Parliament constituency)'),
    ('E14001431', 'Portsmouth North', 'Portsmouth North (UK Parliament constituency)'),
    ('E14001432', 'Portsmouth South', 'Portsmouth South (UK Parliament constituency)'),
    ('E14001433', 'Preston', 'Preston (UK Parliament constituency)'),
    ('E14001434', 'Putney', 'Putney (UK Parliament constituency)'),
    ('E14001435', "Queen's Park and Maida Vale", "Queen's Park and Maida Vale (UK Parliament constituency)"),
    ('E14001436', 'Rawmarsh and Conisbrough', 'Rawmarsh and Conisbrough (UK Parliament constituency)'),
    ('E14001437', 'Rayleigh and Wickford', 'Rayleigh and Wickford (UK Parliament constituency)'),
    ('E14001438', 'Reading Central', 'Reading Central (UK Parliament constituency)'),
    ('E14001439', 'Reading West and Mid Berkshire', 'Reading West and Mid Berkshire (UK Parliament constituency)'),
    ('E14001440', 'Redcar', 'Redcar (UK Parliament constituency)'),
    ('E14001441', 'Redditch', 'Redditch (UK Parliament constituency)'),
    ('E14001442', 'Reigate', 'Reigate (UK Parliament constituency)'),
    ('E14001443', 'Ribble Valley', 'Ribble Valley (UK Parliament constituency)'),
    ('E14001445', 'Richmond Park', 'Richmond Park (UK Parliament constituency)'),
    ('E14001444', 'Richmond and Northallerton', 'Richmond and Northallerton (UK Parliament constituency)'),
    ('E14001446', 'Rochdale', 'Rochdale (UK Parliament constituency)'),
    ('E14001447', 'Rochester and Strood', 'Rochester and Strood (UK Parliament constituency)'),
    ('E14001448', 'Romford', 'Romford (UK Parliament constituency)'),
    ('E14001449', 'Romsey and Southampton North', 'Romsey and Southampton North (UK Parliament constituency)'),
    ('E14001450', 'Rossendale and Darwen', 'Rossendale and Darwen (UK Parliament constituency)'),
    ('E14001451', 'Rother Valley', 'Rother Valley (UK Parliament constituency)'),
    ('E14001452', 'Rotherham', 'Rotherham (UK Parliament constituency)'),
    ('E14001453', 'Rugby', 'Rugby (UK Parliament constituency)'),
    ('E14001454', 'Ruislip, Northwood and Pinner', 'Ruislip, Northwood and Pinner (UK Parliament constituency)'),
    ('E14001455', 'Runcorn and Helsby', 'Runcorn and Helsby (UK Parliament constituency)'),
    ('E14001456', 'Runnymede and Weybridge', 'Runnymede and Weybridge (UK Parliament constituency)'),
    ('E14001457', 'Rushcliffe', 'Rushcliffe (UK Parliament constituency)'),
    ('E14001458', 'Rutland and Stamford', 'Rutland and Stamford (UK Parliament constituency)'),
    ('E14001459', 'Salford', 'Salford (UK Parliament constituency)'),
    ('E14001460', 'Salisbury', 'Salisbury (UK Parliament constituency)'),
    ('E14001461', 'Scarborough and Whitby', 'Scarborough and Whitby (UK Parliament constituency)'),
    ('E14001462', 'Scunthorpe', 'Scunthorpe (UK Parliament constituency)'),
    ('E14001463', 'Sefton Central', 'Sefton Central (UK Parliament constituency)'),
    ('E14001464', 'Selby', 'Selby (UK Parliament constituency)'),
    ('E14001465', 'Sevenoaks', 'Sevenoaks (UK Parliament constituency)'),
    ('E14001466', 'Sheffield Brightside and Hillsborough', 'Sheffield Brightside and Hillsborough (UK Parliament constituency)'),
    ('E14001467', 'Sheffield Central', 'Sheffield Central (UK Parliament constituency)'),
    ('E14001468', 'Sheffield Hallam', 'Sheffield Hallam (UK Parliament constituency)'),
    ('E14001469', 'Sheffield Heeley', 'Sheffield Heeley (UK Parliament constituency)'),
    ('E14001470', 'Sheffield South East', 'Sheffield South East (UK Parliament constituency)'),
    ('E14001471', 'Sherwood Forest', 'Sherwood Forest (UK Parliament constituency)'),
    ('E14001472', 'Shipley', 'Shipley (UK Parliament constituency)'),
    ('E14001473', 'Shrewsbury', 'Shrewsbury (UK Parliament constituency)'),
    ('E14001474', 'Sittingbourne and Sheppey', 'Sittingbourne and Sheppey (UK Parliament constituency)'),
    ('E14001475', 'Skipton and Ripon', 'Skipton and Ripon (UK Parliament constituency)'),
    ('E14001476', 'Sleaford and North Hykeham', 'Sleaford and North Hykeham (UK Parliament constituency)'),
    ('E14001477', 'Slough', 'Slough (UK Parliament constituency)'),
    ('E14001478', 'Smethwick', 'Smethwick (UK Parliament constituency)'),
    ('E14001479', 'Solihull West and Shirley', 'Solihull West and Shirley (UK Parliament constituency)'),
    ('E14001480', 'South Basildon and East Thurrock', 'South Basildon and East Thurrock (UK Parliament constituency)'),
    ('E14001481', 'South Cambridgeshire', 'South Cambridgeshire (UK Parliament constituency)'),
    ('E14001482', 'South Cotswolds', 'South Cotswolds (UK Parliament constituency)'),
    ('E14001483', 'South Derbyshire', 'South Derbyshire (UK Parliament constituency)'),
    ('E14001484', 'South Devon', 'South Devon (UK Parliament constituency)'),
    ('E14001485', 'South Dorset', 'South Dorset (UK Parliament constituency)'),
    ('E14001486', 'South East Cornwall', 'South East Cornwall (UK Parliament constituency)'),
    ('E14001487', 'South Holland and The Deepings', 'South Holland and The Deepings (UK Parliament constituency)'),
    ('E14001488', 'South Leicestershire', 'South Leicestershire (UK Parliament constituency)'),
    ('E14001489', 'South Norfolk', 'South Norfolk (UK Parliament constituency)'),
    ('E14001490', 'South Northamptonshire', 'South Northamptonshire (UK Parliament constituency)'),
    ('E14001491', 'South Ribble', 'South Ribble (UK Parliament constituency)'),
    ('E14001492', 'South Shields', 'South Shields (UK Parliament constituency)'),
    ('E14001493', 'South Shropshire', 'South Shropshire (UK Parliament constituency)'),
    ('E14001494', 'South Suffolk', 'South Suffolk (UK Parliament constituency)'),
    ('E14001495', 'South West Devon', 'South West Devon (UK Parliament constituency)'),
    ('E14001496', 'South West Hertfordshire', 'South West Hertfordshire (UK Parliament constituency)'),
    ('E14001497', 'South West Norfolk', 'South West Norfolk (UK Parliament constituency)'),
    ('E14001498', 'South West Wiltshire', 'South West Wiltshire (UK Parliament constituency)'),
    ('E14001499', 'Southampton Itchen', 'Southampton Itchen (UK Parliament constituency)'),
    ('E14001500', 'Southampton Test', 'Southampton Test (UK Parliament constituency)'),
    ('E14001501', 'Southend East and Rochford', 'Southend East and Rochford (UK Parliament constituency)'),
    ('E14001502', 'Southend West and Leigh', 'Southend West and Leigh (UK Parliament constituency)'),
    ('E14001503', 'Southgate and Wood Green', 'Southgate and Wood Green (UK Parliament constituency)'),
    ('E14001504', 'Southport', 'Southport (UK Parliament constituency)'),
    ('E14001505', 'Spelthorne', 'Spelthorne (UK Parliament constituency)'),
    ('E14001506', 'Spen Valley', 'Spen Valley (UK Parliament constituency)'),
    ('E14001507', 'St Albans', 'St Albans (UK Parliament constituency)'),
    ('E14001508', 'St Austell and Newquay', 'St Austell and Newquay (UK Parliament constituency)'),
    ('E14001509', 'St Helens North', 'St Helens North (UK Parliament constituency)'),
    ('E14001510', 'St Helens South and Whiston', 'St Helens South and Whiston (UK Parliament constituency)'),
    ('E14001511', 'St Ives', 'St Ives (UK Parliament constituency)'),
    ('E14001512', 'St Neots and Mid Cambridgeshire', 'St Neots and Mid Cambridgeshire (UK Parliament constituency)'),
    ('E14001513', 'Stafford', 'Stafford (UK Parliament constituency)'),
    ('E14001514', 'Staffordshire Moorlands', 'Staffordshire Moorlands (UK Parliament constituency)'),
    ('E14001515', 'Stalybridge and Hyde', 'Stalybridge and Hyde (UK Parliament constituency)'),
    ('E14001516', 'Stevenage', 'Stevenage (UK Parliament constituency)'),
    ('E14001517', 'Stockport', 'Stockport (UK Parliament constituency)'),
    ('E14001518', 'Stockton North', 'Stockton North (UK Parliament constituency)'),
    ('E14001519', 'Stockton West', 'Stockton West (UK Parliament constituency)'),
    ('E14001520', 'Stoke-on-Trent Central', 'Stoke-on-Trent Central (UK Parliament constituency)'),
    ('E14001521', 'Stoke-on-Trent North', 'Stoke-on-Trent North (UK Parliament constituency)'),
    ('E14001522', 'Stoke-on-Trent South', 'Stoke-on-Trent South (UK Parliament constituency)'),
    ('E14001523', 'Stone, Great Wyrley and Penkridge', 'Stone, Great Wyrley and Penkridge (UK Parliament constituency)'),
    ('E14001524', 'Stourbridge', 'Stourbridge (UK Parliament constituency)'),
    ('E14001525', 'Stratford and Bow', 'Stratford and Bow (UK Parliament constituency)'),
    ('E14001526', 'Stratford-on-Avon', 'Stratford-on-Avon (UK Parliament constituency)'),
    ('E14001527', 'Streatham and Croydon North', 'Streatham and Croydon North (UK Parliament constituency)'),
    ('E14001528', 'Stretford and Urmston', 'Stretford and Urmston (UK Parliament constituency)'),
    ('E14001529', 'Stroud', 'Stroud (UK Parliament constituency)'),
    ('E14001530', 'Suffolk Coastal', 'Suffolk Coastal (UK Parliament constituency)'),
    ('E14001531', 'Sunderland Central', 'Sunderland Central (UK Parliament constituency)'),
    ('E14001532', 'Surrey Heath', 'Surrey Heath (UK Parliament constituency)'),
    ('E14001533', 'Sussex Weald', 'Sussex Weald (UK Parliament constituency)'),
    ('E14001535', 'Sutton Coldfield', 'Sutton Coldfield (UK Parliament constituency)'),
    ('E14001534', 'Sutton and Cheam', 'Sutton and Cheam (UK Parliament constituency)'),
    ('E14001536', 'Swindon North', 'Swindon North (UK Parliament constituency)'),
    ('E14001537', 'Swindon South', 'Swindon South (UK Parliament constituency)'),
    ('E14001538', 'Tamworth', 'Tamworth (UK Parliament constituency)'),
    ('E14001539', 'Tatton', 'Tatton (UK Parliament constituency)'),
    ('E14001540', 'Taunton and Wellington', 'Taunton and Wellington (UK Parliament constituency)'),
    ('E14001541', 'Telford', 'Telford (UK Parliament constituency)'),
    ('E14001542', 'Tewkesbury', 'Tewkesbury (UK Parliament constituency)'),
    ('E14001543', 'The Wrekin', 'The Wrekin (UK Parliament constituency)'),
    ('E14001544', 'Thirsk and Malton', 'Thirsk and Malton (UK Parliament constituency)'),
    ('E14001545', 'Thornbury and Yate', 'Thornbury and Yate (UK Parliament constituency)'),
    ('E14001546', 'Thurrock', 'Thurrock (UK Parliament constituency)'),
    ('E14001547', 'Tipton and Wednesbury', 'Tipton and Wednesbury (UK Parliament constituency)'),
    ('E14001548', 'Tiverton and Minehead', 'Tiverton and Minehead (UK Parliament constituency)'),
    ('E14001549', 'Tonbridge', 'Tonbridge (UK Parliament constituency)'),
    ('E14001550', 'Tooting', 'Tooting (UK Parliament constituency)'),
    ('E14001551', 'Torbay', 'Torbay (UK Parliament constituency)'),
    ('E14001552', 'Torridge and Tavistock', 'Torridge and Tavistock (UK Parliament constituency)'),
    ('E14001553', 'Tottenham', 'Tottenham (UK Parliament constituency)'),
    ('E14001554', 'Truro and Falmouth', 'Truro and Falmouth (UK Parliament constituency)'),
    ('E14001555', 'Tunbridge Wells', 'Tunbridge Wells (UK Parliament constituency)'),
    ('E14001556', 'Twickenham', 'Twickenham (UK Parliament constituency)'),
    ('E14001557', 'Tynemouth', 'Tynemouth (UK Parliament constituency)'),
    ('E14001558', 'Uxbridge and South Ruislip', 'Uxbridge and South Ruislip (UK Parliament constituency)'),
    ('E14001559', 'Vauxhall and Camberwell Green', 'Vauxhall and Camberwell Green (UK Parliament constituency)'),
    ('E14001560', 'Wakefield and Rothwell', 'Wakefield and Rothwell (UK Parliament constituency)'),
    ('E14001561', 'Wallasey', 'Wallasey (UK Parliament constituency)'),
    ('E14001562', 'Walsall and Bloxwich', 'Walsall and Bloxwich (UK Parliament constituency)'),
    ('E14001563', 'Walthamstow', 'Walthamstow (UK Parliament constituency)'),
    ('E14001564', 'Warrington North', 'Warrington North (UK Parliament constituency)'),
    ('E14001565', 'Warrington South', 'Warrington South (UK Parliament constituency)'),
    ('E14001566', 'Warwick and Leamington', 'Warwick and Leamington (UK Parliament constituency)'),
    ('E14001567', 'Washington and Gateshead South', 'Washington and Gateshead South (UK Parliament constituency)'),
    ('E14001568', 'Watford', 'Watford (UK Parliament constituency)'),
    ('E14001569', 'Waveney Valley', 'Waveney Valley (UK Parliament constituency)'),
    ('E14001570', 'Weald of Kent', 'Weald of Kent (UK Parliament constituency)'),
    ('E14001571', 'Wellingborough and Rushden', 'Wellingborough and Rushden (UK Parliament constituency)'),
    ('E14001572', 'Wells and Mendip Hills', 'Wells and Mendip Hills (UK Parliament constituency)'),
    ('E14001573', 'Welwyn Hatfield', 'Welwyn Hatfield (UK Parliament constituency)'),
    ('E14001574', 'West Bromwich', 'West Bromwich (UK Parliament constituency)'),
    ('E14001575', 'West Dorset', 'West Dorset (UK Parliament constituency)'),
    ('E14001576', 'West Ham and Beckton', 'West Ham and Beckton (UK Parliament constituency)'),
    ('E14001577', 'West Lancashire', 'West Lancashire (UK Parliament constituency)'),
    ('E14001578', 'West Suffolk', 'West Suffolk (UK Parliament constituency)'),
    ('E14001579', 'West Worcestershire', 'West Worcestershire (UK Parliament constituency)'),
    ('E14001580', 'Westmorland and Lonsdale', 'Westmorland and Lonsdale (UK Parliament constituency)'),
    ('E14001581', 'Weston-super-Mare', 'Weston-super-Mare (UK Parliament constituency)'),
    ('E14001582', 'Wetherby and Easingwold', 'Wetherby and Easingwold (UK Parliament constituency)'),
    ('E14001583', 'Whitehaven and Workington', 'Whitehaven and Workington (UK Parliament constituency)'),
    ('E14001584', 'Widnes and Halewood', 'Widnes and Halewood (UK Parliament constituency)'),
    ('E14001585', 'Wigan', 'Wigan (UK Parliament constituency)'),
    ('E14001586', 'Wimbledon', 'Wimbledon (UK Parliament constituency)'),
    ('E14001587', 'Winchester', 'Winchester (UK Parliament constituency)'),
    ('E14001588', 'Windsor', 'Windsor (UK Parliament constituency)'),
    ('E14001589', 'Wirral West', 'Wirral West (UK Parliament constituency)'),
    ('E14001590', 'Witham', 'Witham (UK Parliament constituency)'),
    ('E14001591', 'Witney', 'Witney (UK Parliament constituency)'),
    ('E14001592', 'Woking', 'Woking (UK Parliament constituency)'),
    ('E14001593', 'Wokingham', 'Wokingham (UK Parliament constituency)'),
    ('E14001594', 'Wolverhampton North East', 'Wolverhampton North East (UK Parliament constituency)'),
    ('E14001595', 'Wolverhampton South East', 'Wolverhampton South East (UK Parliament constituency)'),
    ('E14001596', 'Wolverhampton West', 'Wolverhampton West (UK Parliament constituency)'),
    ('E14001597', 'Worcester', 'Worcester (UK Parliament constituency)'),
    ('E14001598', 'Worsley and Eccles', 'Worsley and Eccles (UK Parliament constituency)'),
    ('E14001599', 'Worthing West', 'Worthing West (UK Parliament constituency)'),
    ('E14001600', 'Wycombe', 'Wycombe (UK Parliament constituency)'),
    ('E14001601', 'Wyre Forest', 'Wyre Forest (UK Parliament constituency)'),
    ('E14001602', 'Wythenshawe and Sale East', 'Wythenshawe and Sale East (UK Parliament constituency)'),
    ('E14001603', 'Yeovil', 'Yeovil (UK Parliament constituency)'),
    ('E14001604', 'York Central', 'York Central (UK Parliament constituency)'),
    ('E14001605', 'York Outer', 'York Outer (UK Parliament constituency)'),

    # Scotland (57 seats)
    ('S14000060', 'Aberdeen North', 'Aberdeen North (UK Parliament constituency)'),
    ('S14000061', 'Aberdeen South', 'Aberdeen South (UK Parliament constituency)'),
    ('S14000062', 'Aberdeenshire North and Moray East', 'Aberdeenshire North and Moray East (UK Parliament constituency)'),
    ('S14000063', 'Airdrie and Shotts', 'Airdrie and Shotts (UK Parliament constituency)'),
    ('S14000064', 'Alloa and Grangemouth', 'Alloa and Grangemouth (UK Parliament constituency)'),
    ('S14000065', 'Angus and Perthshire Glens', 'Angus and Perthshire Glens (UK Parliament constituency)'),
    ('S14000066', 'Arbroath and Broughty Ferry', 'Arbroath and Broughty Ferry (UK Parliament constituency)'),
    ('S14000067', 'Argyll, Bute and South Lochaber', 'Argyll, Bute and South Lochaber (UK Parliament constituency)'),
    ('S14000107', 'Ayr, Carrick and Cumnock', 'Ayr, Carrick and Cumnock (UK Parliament constituency)'),
    ('S14000068', 'Bathgate and Linlithgow', 'Bathgate and Linlithgow (UK Parliament constituency)'),
    ('S14000108', 'Berwickshire, Roxburgh and Selkirk', 'Berwickshire, Roxburgh and Selkirk (UK Parliament constituency)'),
    ('S14000069', 'Caithness, Sutherland and Easter Ross', 'Caithness, Sutherland and Easter Ross (UK Parliament constituency)'),
    ('S14000109', 'Central Ayrshire', 'Central Ayrshire (UK Parliament constituency)'),
    ('S14000070', 'Coatbridge and Bellshill', 'Coatbridge and Bellshill (UK Parliament constituency)'),
    ('S14000071', 'Cowdenbeath and Kirkcaldy', 'Cowdenbeath and Kirkcaldy (UK Parliament constituency)'),
    ('S14000072', 'Cumbernauld and Kirkintilloch', 'Cumbernauld and Kirkintilloch (UK Parliament constituency)'),
    ('S14000073', 'Dumfries and Galloway', 'Dumfries and Galloway (UK Parliament constituency)'),
    ('S14000074', 'Dumfriesshire, Clydesdale and Tweeddale', 'Dumfriesshire, Clydesdale and Tweeddale (UK Parliament constituency)'),
    ('S14000075', 'Dundee Central', 'Dundee Central (UK Parliament constituency)'),
    ('S14000076', 'Dunfermline and Dollar', 'Dunfermline and Dollar (UK Parliament constituency)'),
    ('S14000077', 'East Kilbride and Strathaven', 'East Kilbride and Strathaven (UK Parliament constituency)'),
    ('S14000021', 'East Renfrewshire', 'East Renfrewshire (UK Parliament constituency)'),
    ('S14000078', 'Edinburgh East and Musselburgh', 'Edinburgh East and Musselburgh (UK Parliament constituency)'),
    ('S14000079', 'Edinburgh North and Leith', 'Edinburgh North and Leith (UK Parliament constituency)'),
    ('S14000080', 'Edinburgh South', 'Edinburgh South (UK Parliament constituency)'),
    ('S14000081', 'Edinburgh South West', 'Edinburgh South West (UK Parliament constituency)'),
    ('S14000082', 'Edinburgh West', 'Edinburgh West (UK Parliament constituency)'),
    ('S14000083', 'Falkirk', 'Falkirk (UK Parliament constituency)'),
    ('S14000084', 'Glasgow East', 'Glasgow East (UK Parliament constituency)'),
    ('S14000085', 'Glasgow North', 'Glasgow North (UK Parliament constituency)'),
    ('S14000086', 'Glasgow North East', 'Glasgow North East (UK Parliament constituency)'),
    ('S14000087', 'Glasgow South', 'Glasgow South (UK Parliament constituency)'),
    ('S14000088', 'Glasgow South West', 'Glasgow South West (UK Parliament constituency)'),
    ('S14000089', 'Glasgow West', 'Glasgow West (UK Parliament constituency)'),
    ('S14000090', 'Glenrothes and Mid Fife', 'Glenrothes and Mid Fife (UK Parliament constituency)'),
    ('S14000091', 'Gordon and Buchan', 'Gordon and Buchan (UK Parliament constituency)'),
    ('S14000092', 'Hamilton and Clyde Valley', 'Hamilton and Clyde Valley (UK Parliament constituency)'),
    ('S14000093', 'Inverclyde and Renfrewshire West', 'Inverclyde and Renfrewshire West (UK Parliament constituency)'),
    ('S14000094', 'Inverness, Skye and West Ross-shire', 'Inverness, Skye and West Ross-shire (UK Parliament constituency)'),
    ('S14000110', 'Kilmarnock and Loudoun', 'Kilmarnock and Loudoun (UK Parliament constituency)'),
    ('S14000095', 'Livingston', 'Livingston (UK Parliament constituency)'),
    ('S14000096', 'Lothian East', 'Lothian East (UK Parliament constituency)'),
    ('S14000097', 'Mid Dunbartonshire', 'Mid Dunbartonshire (UK Parliament constituency)'),
    ('S14000045', 'Midlothian', 'Midlothian (UK Parliament constituency)'),
    ('S14000098', 'Moray West, Nairn and Strathspey', 'Moray West, Nairn and Strathspey (UK Parliament constituency)'),
    ('S14000099', 'Motherwell, Wishaw and Carluke', 'Motherwell, Wishaw and Carluke (UK Parliament constituency)'),
    ('S14000027', 'Na h-Eileanan an Iar', 'Na h-Eileanan an Iar (UK Parliament constituency)'),
    ('S14000048', 'North Ayrshire and Arran', 'North Ayrshire and Arran (UK Parliament constituency)'),
    ('S14000100', 'North East Fife', 'North East Fife (UK Parliament constituency)'),
    ('S14000051', 'Orkney and Shetland', 'Orkney and Shetland (UK Parliament constituency)'),
    ('S14000101', 'Paisley and Renfrewshire North', 'Paisley and Renfrewshire North (UK Parliament constituency)'),
    ('S14000102', 'Paisley and Renfrewshire South', 'Paisley and Renfrewshire South (UK Parliament constituency)'),
    ('S14000103', 'Perth and Kinross-shire', 'Perth and Kinross-shire (UK Parliament constituency)'),
    ('S14000104', 'Rutherglen', 'Rutherglen (UK Parliament constituency)'),
    ('S14000105', 'Stirling and Strathallan', 'Stirling and Strathallan (UK Parliament constituency)'),
    ('S14000111', 'West Aberdeenshire and Kincardine', 'West Aberdeenshire and Kincardine (UK Parliament constituency)'),
    ('S14000106', 'West Dunbartonshire', 'West Dunbartonshire (UK Parliament constituency)'),

    # Wales (32 seats)
    ('W07000081', 'Aberafan Maesteg', 'Aberafan Maesteg (UK Parliament constituency)'),
    ('W07000082', 'Alyn and Deeside', 'Alyn and Deeside (UK Parliament constituency)'),
    ('W07000083', 'Bangor Aberconwy', 'Bangor Aberconwy (UK Parliament constituency)'),
    ('W07000084', 'Blaenau Gwent and Rhymney', 'Blaenau Gwent and Rhymney (UK Parliament constituency)'),
    ('W07000085', 'Brecon, Radnor and Cwm Tawe', 'Brecon, Radnor and Cwm Tawe (UK Parliament constituency)'),
    ('W07000086', 'Bridgend', 'Bridgend (UK Parliament constituency)'),
    ('W07000087', 'Caerfyrddin', 'Caerfyrddin (UK Parliament constituency)'),
    ('W07000088', 'Caerphilly', 'Caerphilly (UK Parliament constituency)'),
    ('W07000089', 'Cardiff East', 'Cardiff East (UK Parliament constituency)'),
    ('W07000090', 'Cardiff North', 'Cardiff North (UK Parliament constituency)'),
    ('W07000091', 'Cardiff South and Penarth', 'Cardiff South and Penarth (UK Parliament constituency)'),
    ('W07000092', 'Cardiff West', 'Cardiff West (UK Parliament constituency)'),
    ('W07000093', 'Ceredigion Preseli', 'Ceredigion Preseli (UK Parliament constituency)'),
    ('W07000094', 'Clwyd East', 'Clwyd East (UK Parliament constituency)'),
    ('W07000095', 'Clwyd North', 'Clwyd North (UK Parliament constituency)'),
    ('W07000096', 'Dwyfor Meirionnydd', 'Dwyfor Meirionnydd (UK Parliament constituency)'),
    ('W07000097', 'Gower', 'Gower (UK Parliament constituency)'),
    ('W07000098', 'Llanelli', 'Llanelli (UK Parliament constituency)'),
    ('W07000099', 'Merthyr Tydfil and Aberdare', 'Merthyr Tydfil and Aberdare (UK Parliament constituency)'),
    ('W07000100', 'Mid and South Pembrokeshire', 'Mid and South Pembrokeshire (UK Parliament constituency)'),
    ('W07000101', 'Monmouthshire', 'Monmouthshire (UK Parliament constituency)'),
    ('W07000102', 'Montgomeryshire and Glyndŵr', 'Montgomeryshire and Glyndŵr (UK Parliament constituency)'),
    ('W07000103', 'Neath and Swansea East', 'Neath and Swansea East (UK Parliament constituency)'),
    ('W07000104', 'Newport East', 'Newport East (UK Parliament constituency)'),
    ('W07000105', 'Newport West and Islwyn', 'Newport West and Islwyn (UK Parliament constituency)'),
    ('W07000106', 'Pontypridd', 'Pontypridd (UK Parliament constituency)'),
    ('W07000107', 'Rhondda and Ogmore', 'Rhondda and Ogmore (UK Parliament constituency)'),
    ('W07000108', 'Swansea West', 'Swansea West (UK Parliament constituency)'),
    ('W07000109', 'Torfaen', 'Torfaen (UK Parliament constituency)'),
    ('W07000110', 'Vale of Glamorgan', 'Vale of Glamorgan (UK Parliament constituency)'),
    ('W07000111', 'Wrexham', 'Wrexham (UK Parliament constituency)'),
    ('W07000112', 'Ynys Môn', 'Ynys Môn (UK Parliament constituency)'),

    # Northern Ireland (deferred) (18 seats)
    ('N05000001', 'Belfast East', 'Belfast East (UK Parliament constituency)'),
    ('N05000002', 'Belfast North', 'Belfast North (UK Parliament constituency)'),
    ('N05000003', 'Belfast South and Mid Down', 'Belfast South and Mid Down (UK Parliament constituency)'),
    ('N05000004', 'Belfast West', 'Belfast West (UK Parliament constituency)'),
    ('N05000005', 'East Antrim', 'East Antrim (UK Parliament constituency)'),
    ('N05000006', 'East Londonderry', 'East Londonderry (UK Parliament constituency)'),
    ('N05000007', 'Fermanagh and South Tyrone', 'Fermanagh and South Tyrone (UK Parliament constituency)'),
    ('N05000008', 'Foyle', 'Foyle (UK Parliament constituency)'),
    ('N05000009', 'Lagan Valley', 'Lagan Valley (UK Parliament constituency)'),
    ('N05000010', 'Mid Ulster', 'Mid Ulster (UK Parliament constituency)'),
    ('N05000011', 'Newry and Armagh', 'Newry and Armagh (UK Parliament constituency)'),
    ('N05000012', 'North Antrim', 'North Antrim (UK Parliament constituency)'),
    ('N05000013', 'North Down', 'North Down (UK Parliament constituency)'),
    ('N05000014', 'South Antrim', 'South Antrim (UK Parliament constituency)'),
    ('N05000015', 'South Down', 'South Down (UK Parliament constituency)'),
    ('N05000016', 'Strangford', 'Strangford (UK Parliament constituency)'),
    ('N05000017', 'Upper Bann', 'Upper Bann (UK Parliament constituency)'),
    ('N05000018', 'West Tyrone', 'West Tyrone (UK Parliament constituency)'),

]
