"""Registry of all 73 Scottish Parliament constituencies as used at the
2016 and 2021 elections (SPC_DEC_2022 boundary set — the 2014 73-seat map
which was in legal effect through 7 May 2021).

Each tuple is (SPC22CD, name, region, wikipedia_article_title). SPC22CD codes
are real ONS codes sourced from SPC_DEC_2022_SC_BGC; region names come from
the SPC22_SPR22_SC_LU lookup. Wikipedia article titles follow the canonical
``"<name> (Scottish Parliament constituency)"`` pattern (verified live for
every row).

Imported by scripts/17b (per-constituency fetch) and scripts/18b (parser);
shared so they agree on titles + region tags without a third coordination
file (mirrors `_senedd_constituencies.py` and `_ge2024_constituencies.py`).

The post-2026 boundary set (73 different SPC26 codes, S16000151-S16000223)
lives in scripts/09d's ONS fetch; this module is exclusively for the
pre-review 2014 boundaries used at 2016+2021 (PRE_ keys in
data/ward_geoms.json's `spcs_pre_review`).
"""

HOLYROOD_22: list[tuple[str, str, str, str]] = [
    ('S16000074', 'Aberdeen Central',                     'North East Scotland',
     'Aberdeen Central (Scottish Parliament constituency)'),
    ('S16000075', 'Aberdeen Donside',                     'North East Scotland',
     'Aberdeen Donside (Scottish Parliament constituency)'),
    ('S16000076', 'Aberdeen South and North Kincardine',  'North East Scotland',
     'Aberdeen South and North Kincardine (Scottish Parliament constituency)'),
    ('S16000077', 'Aberdeenshire East',                   'North East Scotland',
     'Aberdeenshire East (Scottish Parliament constituency)'),
    ('S16000078', 'Aberdeenshire West',                   'North East Scotland',
     'Aberdeenshire West (Scottish Parliament constituency)'),
    ('S16000079', 'Airdrie and Shotts',                   'Central Scotland',
     'Airdrie and Shotts (Scottish Parliament constituency)'),
    ('S16000080', 'Almond Valley',                        'Lothian',
     'Almond Valley (Scottish Parliament constituency)'),
    ('S16000081', 'Angus North and Mearns',               'North East Scotland',
     'Angus North and Mearns (Scottish Parliament constituency)'),
    ('S16000082', 'Angus South',                          'North East Scotland',
     'Angus South (Scottish Parliament constituency)'),
    ('S16000083', 'Argyll and Bute',                      'Highlands and Islands',
     'Argyll and Bute (Scottish Parliament constituency)'),
    ('S16000084', 'Ayr',                                  'South Scotland',
     'Ayr (Scottish Parliament constituency)'),
    ('S16000085', 'Banffshire and Buchan Coast',          'North East Scotland',
     'Banffshire and Buchan Coast (Scottish Parliament constituency)'),
    ('S16000086', 'Caithness, Sutherland and Ross',       'Highlands and Islands',
     'Caithness, Sutherland and Ross (Scottish Parliament constituency)'),
    ('S16000087', 'Carrick, Cumnock and Doon Valley',     'South Scotland',
     'Carrick, Cumnock and Doon Valley (Scottish Parliament constituency)'),
    ('S16000088', 'Clackmannanshire and Dunblane',        'Mid Scotland and Fife',
     'Clackmannanshire and Dunblane (Scottish Parliament constituency)'),
    ('S16000089', 'Clydebank and Milngavie',              'West Scotland',
     'Clydebank and Milngavie (Scottish Parliament constituency)'),
    ('S16000090', 'Clydesdale',                           'South Scotland',
     'Clydesdale (Scottish Parliament constituency)'),
    ('S16000092', 'Cowdenbeath',                          'Mid Scotland and Fife',
     'Cowdenbeath (Scottish Parliament constituency)'),
    ('S16000093', 'Cumbernauld and Kilsyth',              'Central Scotland',
     'Cumbernauld and Kilsyth (Scottish Parliament constituency)'),
    ('S16000094', 'Cunninghame North',                    'West Scotland',
     'Cunninghame North (Scottish Parliament constituency)'),
    ('S16000095', 'Cunninghame South',                    'West Scotland',
     'Cunninghame South (Scottish Parliament constituency)'),
    ('S16000096', 'Dumbarton',                            'West Scotland',
     'Dumbarton (Scottish Parliament constituency)'),
    ('S16000097', 'Dumfriesshire',                        'South Scotland',
     'Dumfriesshire (Scottish Parliament constituency)'),
    ('S16000098', 'Dundee City East',                     'North East Scotland',
     'Dundee City East (Scottish Parliament constituency)'),
    ('S16000099', 'Dundee City West',                     'North East Scotland',
     'Dundee City West (Scottish Parliament constituency)'),
    ('S16000100', 'Dunfermline',                          'Mid Scotland and Fife',
     'Dunfermline (Scottish Parliament constituency)'),
    ('S16000101', 'East Kilbride',                        'Central Scotland',
     'East Kilbride (Scottish Parliament constituency)'),
    ('S16000102', 'East Lothian',                         'South Scotland',
     'East Lothian (Scottish Parliament constituency)'),
    ('S16000103', 'Eastwood',                             'West Scotland',
     'Eastwood (Scottish Parliament constituency)'),
    ('S16000104', 'Edinburgh Central',                    'Lothian',
     'Edinburgh Central (Scottish Parliament constituency)'),
    ('S16000105', 'Edinburgh Eastern',                    'Lothian',
     'Edinburgh Eastern (Scottish Parliament constituency)'),
    ('S16000106', 'Edinburgh Northern and Leith',         'Lothian',
     'Edinburgh Northern and Leith (Scottish Parliament constituency)'),
    ('S16000107', 'Edinburgh Pentlands',                  'Lothian',
     'Edinburgh Pentlands (Scottish Parliament constituency)'),
    ('S16000108', 'Edinburgh Southern',                   'Lothian',
     'Edinburgh Southern (Scottish Parliament constituency)'),
    ('S16000109', 'Edinburgh Western',                    'Lothian',
     'Edinburgh Western (Scottish Parliament constituency)'),
    ('S16000110', 'Na h-Eileanan an Iar',                 'Highlands and Islands',
     'Na h-Eileanan an Iar (Scottish Parliament constituency)'),
    ('S16000111', 'Ettrick, Roxburgh and Berwickshire',   'South Scotland',
     'Ettrick, Roxburgh and Berwickshire (Scottish Parliament constituency)'),
    ('S16000112', 'Falkirk East',                         'Central Scotland',
     'Falkirk East (Scottish Parliament constituency)'),
    ('S16000113', 'Falkirk West',                         'Central Scotland',
     'Falkirk West (Scottish Parliament constituency)'),
    ('S16000114', 'Galloway and West Dumfries',           'South Scotland',
     'Galloway and West Dumfries (Scottish Parliament constituency)'),
    ('S16000115', 'Glasgow Anniesland',                   'Glasgow',
     'Glasgow Anniesland (Scottish Parliament constituency)'),
    ('S16000116', 'Glasgow Cathcart',                     'Glasgow',
     'Glasgow Cathcart (Scottish Parliament constituency)'),
    ('S16000117', 'Glasgow Kelvin',                       'Glasgow',
     'Glasgow Kelvin (Scottish Parliament constituency)'),
    ('S16000118', 'Glasgow Maryhill and Springburn',      'Glasgow',
     'Glasgow Maryhill and Springburn (Scottish Parliament constituency)'),
    ('S16000119', 'Glasgow Pollok',                       'Glasgow',
     'Glasgow Pollok (Scottish Parliament constituency)'),
    ('S16000121', 'Glasgow Shettleston',                  'Glasgow',
     'Glasgow Shettleston (Scottish Parliament constituency)'),
    ('S16000122', 'Glasgow Southside',                    'Glasgow',
     'Glasgow Southside (Scottish Parliament constituency)'),
    ('S16000123', 'Greenock and Inverclyde',              'West Scotland',
     'Greenock and Inverclyde (Scottish Parliament constituency)'),
    ('S16000124', 'Hamilton, Larkhall and Stonehouse',    'Central Scotland',
     'Hamilton, Larkhall and Stonehouse (Scottish Parliament constituency)'),
    ('S16000125', 'Inverness and Nairn',                  'Highlands and Islands',
     'Inverness and Nairn (Scottish Parliament constituency)'),
    ('S16000126', 'Kilmarnock and Irvine Valley',         'South Scotland',
     'Kilmarnock and Irvine Valley (Scottish Parliament constituency)'),
    ('S16000127', 'Kirkcaldy',                            'Mid Scotland and Fife',
     'Kirkcaldy (Scottish Parliament constituency)'),
    ('S16000128', 'Linlithgow',                           'Lothian',
     'Linlithgow (Scottish Parliament constituency)'),
    ('S16000129', 'Mid Fife and Glenrothes',              'Mid Scotland and Fife',
     'Mid Fife and Glenrothes (Scottish Parliament constituency)'),
    ('S16000130', 'Midlothian North and Musselburgh',     'Lothian',
     'Midlothian North and Musselburgh (Scottish Parliament constituency)'),
    ('S16000131', 'Midlothian South, Tweeddale and Lauderdale', 'South Scotland',
     'Midlothian South, Tweeddale and Lauderdale (Scottish Parliament constituency)'),
    ('S16000132', 'Moray',                                'Highlands and Islands',
     'Moray (Scottish Parliament constituency)'),
    ('S16000133', 'Motherwell and Wishaw',                'Central Scotland',
     'Motherwell and Wishaw (Scottish Parliament constituency)'),
    ('S16000134', 'North East Fife',                      'Mid Scotland and Fife',
     'North East Fife (Scottish Parliament constituency)'),
    ('S16000135', 'Orkney Islands',                       'Highlands and Islands',
     'Orkney Islands (constituency)'),
    ('S16000136', 'Paisley',                              'West Scotland',
     'Paisley (Scottish Parliament constituency)'),
    ('S16000137', 'Perthshire North',                     'Mid Scotland and Fife',
     'Perthshire North (Scottish Parliament constituency)'),
    ('S16000138', 'Perthshire South and Kinross-shire',   'Mid Scotland and Fife',
     'Perthshire South and Kinross-shire (Scottish Parliament constituency)'),
    ('S16000139', 'Renfrewshire North and West',          'West Scotland',
     'Renfrewshire North and West (Scottish Parliament constituency)'),
    ('S16000140', 'Renfrewshire South',                   'West Scotland',
     'Renfrewshire South (Scottish Parliament constituency)'),
    ('S16000141', 'Rutherglen',                           'Glasgow',
     'Rutherglen (Scottish Parliament constituency)'),
    ('S16000142', 'Shetland Islands',                     'Highlands and Islands',
     'Shetland Islands (Scottish Parliament constituency)'),
    ('S16000143', 'Skye, Lochaber and Badenoch',          'Highlands and Islands',
     'Skye, Lochaber and Badenoch (Scottish Parliament constituency)'),
    ('S16000144', 'Stirling',                             'Mid Scotland and Fife',
     'Stirling (Scottish Parliament constituency)'),
    ('S16000146', 'Uddingston and Bellshill',             'Central Scotland',
     'Uddingston and Bellshill (Scottish Parliament constituency)'),
    ('S16000148', 'Strathkelvin and Bearsden',            'West Scotland',
     'Strathkelvin and Bearsden (Scottish Parliament constituency)'),
    ('S16000149', 'Coatbridge and Chryston',              'Central Scotland',
     'Coatbridge and Chryston (Scottish Parliament constituency)'),
    ('S16000150', 'Glasgow Provan',                       'Glasgow',
     'Glasgow Provan (Scottish Parliament constituency)'),
]

assert len(HOLYROOD_22) == 73, f'expected 73 entries, found {len(HOLYROOD_22)}'
assert len({r[0] for r in HOLYROOD_22}) == 73, 'duplicate SPC22CD'
